# Generated by Django 6.1 on 2026-08-05 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('unite_par_defaut', models.CharField(max_length=20)),
                ('categorie_rayon', models.CharField(choices=[('fruits_legumes', 'Fruits & légumes'), ('epicerie', 'Épicerie'), ('surgeles', 'Surgelés'), ('produits_laitiers', 'Produits laitiers'), ('viande_poisson', 'Viande & poisson'), ('boissons', 'Boissons'), ('autre', 'Autre')], default='autre', max_length=20)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recettes/')),
                ('temps_preparation_min', models.PositiveIntegerField()),
                ('temps_cuisson_min', models.PositiveIntegerField(blank=True, default=0)),
                ('portions_defaut', models.PositiveIntegerField(default=4)),
                ('score_nutritionnel', models.CharField(choices=[('leger', 'Léger'), ('equilibre', 'Équilibré'), ('gourmand', 'Gourmand')], default='equilibre', max_length=20)),
                ('derniere_cuisson_le', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='recettes.recette')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='RecetteIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unite', models.CharField(max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recettes.ingredient')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recette_ingredients', to='recettes.recette')),
            ],
        ),
        migrations.AddField(
            model_name='recette',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recettes', to='recettes.tag'),
        ),
    ]
