# Generated by Django 6.1 on 2026-08-06 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_time', models.CharField(choices=[('lunch', 'Midi'), ('dinner', 'Soir')], max_length=10)),
                ('planned_servings', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_slots', to='recipes.recipe')),
            ],
            options={
                'ordering': ['date', 'meal_time'],
                'unique_together': {('date', 'meal_time')},
            },
        ),
    ]
