# Generated by Django 6.1 on 2026-08-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shoppinglist_deal_shoppinglistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit', models.CharField(max_length=20)),
                ('location', models.CharField(choices=[('pantry', 'Placard'), ('fridge', 'Frigo'), ('freezer', 'Congélateur')], default='pantry', max_length=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='recipes.ingredient')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('expiry_date'), nulls_last=True), 'id'],
            },
        ),
    ]
