# Generated by Django 6.1 on 2026-08-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories_kcal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_mode',
            field=models.CharField(blank=True, choices=[('oven', 'Four'), ('stovetop', 'Plaque'), ('no_cook', 'Sans cuisson'), ('bbq', 'BBQ')], max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Facile'), ('medium', 'Intermédiaire'), ('hard', 'Difficile')], max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='equipment_needed',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='estimated_cost',
            field=models.CharField(blank=True, choices=[('low', 'Économique'), ('medium', 'Moyen'), ('high', 'Coûteux')], max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fridge_shelf_life_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_freezable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_moment',
            field=models.CharField(blank=True, choices=[('breakfast', 'Petit-déjeuner'), ('lunch', 'Lunch'), ('dinner', 'Souper'), ('snack', 'Collation')], max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein_g',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rest_time_min',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='seasonality_months',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
