# Generated by Django 6.1 on 2026-08-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='reference_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='reference_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
