# Generated by Django 6.1 on 2026-08-08 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredient_reference_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('sourdough', 'Levain'), ('marinade', 'Marinade'), ('brewing', 'Brassage'), ('fermentation', 'Lacto-fermentation'), ('other', 'Autre')], default='other', max_length=20)),
                ('started_on', models.DateField(default=datetime.date.today)),
                ('ready_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'long processes',
                'ordering': [models.OrderBy(models.F('ready_on'), nulls_last=True), '-started_on'],
            },
        ),
    ]
